import 'package:flutter/material.dart';

List<List<Color>> colorsGrid = [
  [
    Colors.grey.shade800,
    Colors.grey.shade800,
    Colors.grey.shade800,
    Colors.grey.shade800,
    Colors.grey.shade800
  ],
  [
    Colors.grey.shade800,
    Colors.grey.shade800,
    Colors.grey.shade800,
    Colors.grey.shade800,
    Colors.grey.shade800
  ],
  [
    Colors.grey.shade800,
    Colors.grey.shade800,
    Colors.grey.shade800,
    Colors.grey.shade800,
    Colors.grey.shade800
  ],
  [
    Colors.grey.shade800,
    Colors.grey.shade800,
    Colors.grey.shade800,
    Colors.grey.shade800,
    Colors.grey.shade800
  ],
  [
    Colors.grey.shade800,
    Colors.grey.shade800,
    Colors.grey.shade800,
    Colors.grey.shade800,
    Colors.grey.shade800
  ],
  [
    Colors.grey.shade800,
    Colors.grey.shade800,
    Colors.grey.shade800,
    Colors.grey.shade800,
    Colors.grey.shade800
  ],
];
